# Generated by Django 5.0.6 on 2026-05-09 09:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('silos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMFPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('sigle', models.CharField(blank=True, max_length=20, verbose_name='sigle')),
                ('contact_nom', models.CharField(max_length=150, verbose_name='contact principal')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('taux_interet_mensuel', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name="taux d'intérêt mensuel (%)")),
                ('delai_traitement_jours', models.PositiveIntegerField(default=5, verbose_name='délai de traitement (jours)')),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IMF partenaire',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='OffreAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantité souhaitée (kg)')),
                ('prix_propose_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix proposé (FCFA/kg)')),
                ('region_preferee', models.CharField(blank=True, max_length=100, verbose_name='région préférée')),
                ('delai_souhaite_jours', models.PositiveSmallIntegerField(default=30, verbose_name='délai souhaité (jours)')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('NEGOCIATION', 'En négociation'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée'), ('FINALISEE', 'Finalisée')], default='SOUMISE', max_length=15, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('date_offre', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_achat', to=settings.AUTH_USER_MODEL)),
                ('denree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silos.denree')),
                ('depots_cibles', models.ManyToManyField(blank=True, related_name='offres', to='silos.depot')),
            ],
            options={
                'verbose_name': "offre d'achat",
                'ordering': ['-date_offre'],
            },
        ),
        migrations.CreateModel(
            name='PrixMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='National', max_length=100, verbose_name='région')),
                ('pays', models.CharField(default='Sénégal', max_length=50, verbose_name='pays')),
                ('prix_kg_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix (FCFA/kg)')),
                ('prix_min_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix min (FCFA/kg)')),
                ('prix_max_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix max (FCFA/kg)')),
                ('source', models.CharField(default='DAPSA/OMA', max_length=100, verbose_name='source')),
                ('date_maj', models.DateField(auto_now_add=True, verbose_name='date de mise à jour')),
                ('semaine', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('denree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='silos.denree')),
            ],
            options={
                'verbose_name': 'prix de marché',
                'ordering': ['-date_maj', 'denree'],
            },
        ),
        migrations.CreateModel(
            name='ProfilAgriculteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(blank=True, max_length=150, verbose_name='village')),
                ('superficie_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='superficie (ha)')),
                ('numero_agriculteur', models.CharField(blank=True, max_length=30, unique=True, verbose_name='numéro agriculteur')),
                ('score_credit', models.PositiveSmallIntegerField(default=50, verbose_name='score de crédit')),
                ('score_calcule_le', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, verbose_name='présentation')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='silos.commune')),
                ('cultures_principales', models.ManyToManyField(blank=True, to='silos.denree')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_agriculteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil agriculteur',
            },
        ),
        migrations.CreateModel(
            name='RecommandationVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_recommandee', models.CharField(choices=[('ATTENDRE', 'Attendre'), ('VENDRE', 'Vendre maintenant'), ('PARTIEL', 'Vendre partiellement')], max_length=10, verbose_name='action')),
                ('message_fr', models.TextField(verbose_name='message (FR)')),
                ('message_wo', models.TextField(blank=True, verbose_name='message (Wolof)')),
                ('message_en', models.TextField(blank=True, verbose_name='message (EN)')),
                ('prix_actuel_fcfa', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('prix_prevu_4sem_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_prevu_8sem_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('validee_par_admin', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('valide_jusqu_au', models.DateField(blank=True, null=True)),
                ('denree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silos.denree')),
            ],
            options={
                'verbose_name': 'recommandation de vente',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total_fcfa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_gc_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='commission GC')),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('facture_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('offre', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='core.offreachat')),
                ('retrait', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='silos.retrait')),
            ],
            options={
                'verbose_name': 'transaction',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='WarrantageCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande_fcfa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant demandé (FCFA)')),
                ('montant_accorde_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='montant accordé (FCFA)')),
                ('taux_interet_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="taux d'intérêt mensuel (%)")),
                ('duree_mois', models.PositiveSmallIntegerField(default=3, verbose_name='durée (mois)')),
                ('score_credit_snapshot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('EN_INSTRUCTION', 'En instruction'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé'), ('VIRE', 'Fonds virés'), ('REMBOURSE', 'Remboursé'), ('EN_DEFAUT', 'En défaut')], default='SOUMIS', max_length=20, verbose_name='statut')),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif de refus')),
                ('mode_paiement', models.CharField(default='Wave', max_length=50, verbose_name='mode de paiement')),
                ('numero_paiement', models.CharField(blank=True, max_length=30, verbose_name='numéro Wave/Orange Money')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('date_virement', models.DateTimeField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_remboursement', models.DateTimeField(blank=True, null=True)),
                ('dossier_pdf', models.FileField(blank=True, null=True, upload_to='warrantages/')),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warrantages', to=settings.AUTH_USER_MODEL)),
                ('depot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warrantage', to='silos.depot')),
                ('imf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='core.imfpartenaire')),
            ],
            options={
                'verbose_name': 'warrantage / crédit',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('SMS', 'SMS'), ('APP', 'In-App'), ('EMAIL', 'Email')], max_length=10, verbose_name='canal')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='titre')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('contenu_traduit', models.TextField(blank=True, verbose_name='contenu traduit')),
                ('langue_envoi', models.CharField(default='fr', max_length=5, verbose_name="langue d'envoi")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('LU', 'Lu')], default='EN_ATTENTE', max_length=15, verbose_name='statut')),
                ('erreur', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('lu_le', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['destinataire', 'statut'], name='core_notifi_destina_9d25d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contenu', models.CharField(choices=[('RECU', 'Reçu de dépôt'), ('ALERTE', 'Alerte système'), ('RECOMMANDATION', 'Recommandation de vente'), ('SMS', 'SMS agriculteur'), ('NOTIFICATION', 'Notification'), ('RAPPORT', 'Rapport'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='type de contenu')),
                ('texte_source', models.TextField(verbose_name='texte source')),
                ('texte_traduit', models.TextField(verbose_name='texte traduit')),
                ('langue_source', models.CharField(default='fr', max_length=5, verbose_name='langue source')),
                ('langue_cible', models.CharField(max_length=5, verbose_name='langue cible')),
                ('moteur', models.CharField(choices=[('NLLB200', 'Meta NLLB-200'), ('GOOGLE', 'Google Translate'), ('MANUEL', 'Traduction manuelle')], default='NLLB200', max_length=10, verbose_name='moteur de traduction')),
                ('note_qualite', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note qualité (1-5)')),
                ('suggestion_correction', models.TextField(blank=True, verbose_name='suggestion de correction')),
                ('correction_traitee', models.BooleanField(default=False, verbose_name='correction traitée')),
                ('temps_traitement_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='temps (ms)')),
                ('depuis_cache', models.BooleanField(default=False, verbose_name='depuis cache')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traductions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de traduction',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['user', 'cree_le'], name='core_transl_user_id_9d2404_idx'), models.Index(fields=['langue_cible', 'cree_le'], name='core_transl_langue__be0141_idx')],
            },
        ),
    ]
