# Generated by Django 5.0.6 on 2026-05-09 09:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('region', models.CharField(max_length=100, verbose_name='région')),
                ('departement', models.CharField(blank=True, max_length=100, verbose_name='département')),
                ('pays', models.CharField(default='Sénégal', max_length=50, verbose_name='pays')),
                ('code_postal', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'commune',
                'ordering': ['region', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Denree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('nom_wolof', models.CharField(blank=True, max_length=100, verbose_name='nom en wolof')),
                ('nom_anglais', models.CharField(blank=True, max_length=100, verbose_name='nom en anglais')),
                ('temperature_min', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('temperature_max', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('humidite_max', models.DecimalField(decimal_places=2, default=13, max_digits=5)),
                ('unite', models.CharField(default='kg', max_length=20, verbose_name='unité')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'denrée',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(editable=False, max_length=30, unique=True, verbose_name='numéro de reçu')),
                ('quantite_initiale_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='quantité initiale (kg)')),
                ('quantite_disponible_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantité disponible (kg)')),
                ('prix_reference_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix de référence (FCFA/kg)')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='depots/', verbose_name='photo')),
                ('statut', models.CharField(choices=[('ACTIF', 'En stock'), ('PARTIEL', 'Partiellement retiré'), ('RETIRE', 'Retiré'), ('VENDU', 'Vendu'), ('WARRANTE', 'Sous warrantage')], default='ACTIF', max_length=20, verbose_name='statut')),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='date de dépôt')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="date d'expiration estimée")),
                ('date_retrait_effectif', models.DateTimeField(blank=True, null=True)),
                ('recu_pdf', models.FileField(blank=True, null=True, upload_to='recus/', verbose_name='reçu PDF')),
                ('agriculteur', models.ForeignKey(limit_choices_to={'role': 'AGRICULTEUR'}, on_delete=django.db.models.deletion.PROTECT, related_name='depots', to=settings.AUTH_USER_MODEL)),
                ('denree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='silos.denree')),
                ('gestionnaire', models.ForeignKey(limit_choices_to={'role': 'GESTIONNAIRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dépôt',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='quantité retirée (kg)')),
                ('type_retrait', models.CharField(choices=[('RETRAIT', "Retrait par l'agriculteur"), ('VENTE', 'Vente via la plateforme')], default='RETRAIT', max_length=10, verbose_name='type')),
                ('prix_vente_fcfa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix de vente (FCFA/kg)')),
                ('observations', models.TextField(blank=True)),
                ('bon_sortie_pdf', models.FileField(blank=True, null=True, upload_to='bons_sortie/')),
                ('date_retrait', models.DateTimeField(auto_now_add=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits', to='silos.depot')),
                ('gestionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'retrait',
                'ordering': ['-date_retrait'],
            },
        ),
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom du silo')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code unique')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacite_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacité (kg)')),
                ('stock_actuel_kg', models.PositiveIntegerField(default=0, verbose_name='stock actuel (kg)')),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='température (°C)')),
                ('humidite_pourcent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='humidité (%)')),
                ('derniere_mesure', models.DateTimeField(blank=True, null=True, verbose_name='dernière mesure')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('MAINTENANCE', 'En maintenance'), ('INACTIF', 'Inactif'), ('PLEIN', 'Capacité maximale atteinte')], default='ACTIF', max_length=20, verbose_name='statut')),
                ('sante', models.CharField(choices=[('VERT', 'Optimal'), ('ORANGE', 'Surveillance requise'), ('ROUGE', 'Intervention urgente')], default='VERT', max_length=10, verbose_name='santé')),
                ('date_installation', models.DateField(blank=True, null=True, verbose_name="date d'installation")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='silos', to='silos.commune')),
                ('gestionnaire', models.ForeignKey(limit_choices_to={'role': 'GESTIONNAIRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silos_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'silo',
                'ordering': ['commune', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='depot',
            name='silo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='silos.silo'),
        ),
        migrations.CreateModel(
            name='AlerteSilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('TEMPERATURE', 'Température anormale'), ('HUMIDITE', 'Humidité excessive'), ('RONGEUR', 'Présence de rongeurs'), ('REMPLISSAGE', 'Capacité maximale atteinte'), ('AUTRE', 'Autre anomalie')], max_length=20, verbose_name='type')),
                ('niveau', models.CharField(choices=[('VERT', 'Normal'), ('ORANGE', 'Surveillance'), ('ROUGE', 'Urgence')], max_length=10, verbose_name='niveau')),
                ('message', models.TextField(verbose_name='message')),
                ('valeur_mesuree', models.CharField(blank=True, max_length=50, verbose_name='valeur mesurée')),
                ('valeur_seuil', models.CharField(blank=True, max_length=50, verbose_name='valeur seuil')),
                ('est_acquittee', models.BooleanField(default=False, verbose_name='acquittée')),
                ('commentaire_acquittement', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('acquittee_le', models.DateTimeField(blank=True, null=True)),
                ('acquittee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_acquittees', to=settings.AUTH_USER_MODEL)),
                ('silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='silos.silo')),
            ],
            options={
                'verbose_name': 'alerte silo',
                'ordering': ['-cree_le'],
            },
        ),
    ]
